### PR TITLE
Correct the README heading URL

### PR DESCRIPTION
**Pull request by taizhng**
Amazing PR

Top contributor

Much wow

### CODE REVIEW

**Review by eamonma — APPROVED** [review]
lgtm, thanks.

**Comment by eamonma** [comment]
@taizhng Please change the target of the PR to develop

**Review by eamonma — APPROVED** [review]
lgtm, thanks.

**Comment by taizhng** [comment]
> @taizhng Please change the target of the PR to develop

My apologies. As there were not contribution docs I did not know this. What does changing the target to develop do?

**Comment by eamonma** [comment]
> My apologies. As there were not contribution docs I did not know this. What does changing the target to develop do?

That's fair. If you wish, you can help out by incorporating [https://www.contributor-covenant.org/](https://www.contributor-covenant.org/) this into our existing (albeit limited) documentation.

**Pull request merged**
